codecov:
  branch: master
  strict_yaml_branch: master
  require_ci_to_pass: true
  max_report_age: off

coverage:
  precision: 2
  round: down
  range: "33...80"

  status:
    project: yes
      default:
        # basic
        target: 80%
        threshold: 1%
        base: auto
        flags: null
        paths: null
        # advanced
        branches: null
        if_not_found: success
        if_ci_failed: error
        informational: true
        only_pulls: true
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: