codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "80...100"

  status:
    project: yes
      default:
        # basic
        target: auto
        threshold: null
        base: auto
        flags: null
        paths: null
        # advanced
        branches: null
        if_not_found: success
        if_ci_failed: error
        informational: False
        only_pulls: false
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: