/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package by.academy.jc.sergeichik;

public class CalculatorUtils {

    public static int sum(int a, int b) {

        return (a + b) + (a * b);
    }
    public static double division(double a, double b) {

        return (a * b) / (a + b);
    }
    public static int increment(int a, double b) {

        return (int) ((a * 10) / ++b);
    }
}