/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package by.academy.jc.sergeichik;

public class Calculator {

    public static int sum(int a, int b) {

        int result = (a + b) + (a * b);
        return result;
    }
}