/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package by.academy.jc.sergeichik;

public class Solution {

    public int solution (int x, int y, int d){
        int i = 0;
        for(i=0; x<=y; i++){
            x+=d;
        }
        return i;
    }
    public int solution1 (int x, int y, int d){
        int i = 0;
        while (x<=y){
            x+=d;
            i++;
        }
        return i;
    }
    public int solution2 (int x, int y, int d){
        int i = 0;
        do{
            x+=d;
            i++;
        } while (x<=y);
        return i;
    }
}
