/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package by.academy.jc.sergeichik;

public class Solution {

    public int solution1 (int x, int y, int d){
        int i = 0;
        while (x<=y){
            x+=d;
            i++;
        }
        return i;
    }
}
