/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package by.academy.jc;

public class Sum {
    // sum int
    public int sum (int a, int b){
        return (a + b + a * b);
    }
    //sum double
    public double sum (double a, double b){
        return (a + b + a * b);
    }
}

